// <auto-generated />
using System;
using Candlewire.Identity.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Candlewire.Identity.Server.Migrations.PersistenceDb
{
    [DbContext(typeof(PersistenceDbContext))]
    partial class PersistenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Candlewire.Identity.Server.Contexts.PersistenceItem", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("PersistenceData")
                        .HasColumnType("text");

                    b.Property<DateTime>("PersistenceExpiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PersistenceKey")
                        .HasColumnType("text");

                    b.Property<string>("PersistenceToken")
                        .HasColumnType("text");

                    b.HasKey("PersistenceId");

                    b.ToTable("PersistenceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
